# Generated by Django 3.2.3 on 2021-05-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='brand',
            field=models.CharField(max_length=20),
        ),
    ]
