# Generated by Django 3.2.3 on 2021-05-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapi', '0002_alter_card_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
