# Generated by Django 3.2.3 on 2021-05-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapi', '0003_alter_card_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='brand',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='card',
            name='city',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='url',
            field=models.CharField(max_length=250),
        ),
    ]
